name: Test Code

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - test-ci # always want to including test-ci for testing gh-action
    paths-ignore:
      - 'README.md'

jobs:
  test-code:
    name: Test
    strategy:
      matrix:
        toolchain:
          - stable
    runs-on:                       ubuntu-latest
    container:
      image:                       paritytech/ci-linux:production
    env:
      RUST_BACKTRACE:              full
      CARGO_INCREMENTAL:           0
      SCCACHE_IDLE_TIMEOUT:        0
      CMAKE_C_COMPILER_LAUNCHER:   sccache
      CMAKE_CXX_COMPILER_LAUNCHER: sccache

    steps:
      - name:                      Cancel previous runs
        uses:                      styfle/cancel-workflow-action@0.4.1
        with:
          access_token:            ${{ github.token }}

      - name:                      Rust version
        shell:                     bash
        run:                       |
          rustup show

      - name:                      Checkout sources & submodules
        uses:                      actions/checkout@v2
        with:
          fetch-depth:             5
          submodules:              recursive

      - name:                      Rust Cache
        uses:                      Swatinem/rust-cache@v1.2.0

      - name:                      Sccache stats
        shell:                     bash
        run:                       |
          sccache --show-stats

      ## --- Test stage ---

      - name:                      Run all recipes tests
        uses:                      actions-rs/cargo@master
        with:
          command:                 test
          args:                    --all --verbose
